apiVersion: batch/v1
kind: Job
metadata:
  name: ha-nginx-job-parallel-completion
spec:
  completions: 2
  parallelism: 4
  backoffLimit: 2
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: ha-nginx-job-parallel-completion-c
          image: nginx:1.10.1
          command:
            - "/bin/bash"
            - "-c"
            - "date +'Hello from ha-nginx-job-parallel-completion %Y-%m-%d %H:%M:%S'"
