apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ha-persistent-volume-claim-1
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
